name: git action tag
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version and push tag
        uses: actions/checkout@v2
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}