name: Create/update tag
on:
  push:
    branch: "main"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sourav-crossml/gitactions@v1
        with:
          tag: "latest"
          message: "Latest release"