name: git action tag
on:
  push:
    branches:
      - main
    tags:        
      - v
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version and push tag
        uses: actions/checkout@v2
       